# -*- coding: utf-8 -*-
"""aggregate_ccp.json -> SUMMARY_CCP.md(決定論・API無し)。数値は全てaggregate_ccp.jsonから埋め込む。"""
import json, os
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
os.chdir(ROOT)
EV = "er052_output/open233_control_checker_polysemy_trial_01/eval"
A = json.load(open(EV + "/aggregate_ccp.json", encoding="utf-8"))
R = A["rollback"]; S = A["overall_stats"]; J = A["judgement"]; T = A["themes"]; E = A["evaluators"]
f = lambda v, n: "%.2f" % (v / n)
pct = lambda x: "%.1f%%" % (x * 100)
L = []
w = L.append
w("# SUMMARY_CCP: OPEN-233-CONTROL-CHECKER-POLYSEMY-PRODUCTION-PATH-TRIAL-01 委任_03 盲検評価の集計(¥0、2026-10-07)")
w("")
w("到達Status: **EVALUATED(人間確認待ち)**。Trial(DEV)。Production変更なし。API費用 ¥0(既存成果物の集計のみ)。評価JSONは書換えていない。")
w("**重大/Rollback判定は全て評価インスタンスの単独判定(人間確認前)=暫定**。確定は `HUMAN_REVIEW_PACK.md` のユーザー回答後(`preregistration_01.md` 6節)。")
w("")
w("## MAP開封記録")
w("- 開封時刻: 2026-10-07 20:21頃(最初に `eval/_private/MAP_ccp.json` を読込)。集計script `docs/pm/control_checker_polysemy_trial_01/tools/aggregate_eval_ccp.py` の実行時刻: %s。" % A["opened_at"])
w("- 理由: 評価者A/B/C(各6記事=18記事JSON)+rollback_X(Meta10件)が全員分出揃い、Fableが委任_03で集計開始を指示した。評価JSONは読取専用。")
w("- 検算: 記事JSON %d件(MAP解決不能 %d)、rollback_X %d件、ng_items件数とstages値の不一致 %d件、評価者A/B/Cの担当6記事ずつ割付どおり。" % (A["check"]["articles"], len(A["check"]["map_missing"]), A["check"]["rollback_x_n"], len(A["check"]["ng_items_vs_stages_mismatch"])))
w("")
w("## 結論の要点(暫定)")
w("- 重大あり記事 **0/18**(片側95%上限 15.3%)。Rollback JA R2 の誤読 **0/10**、累積 **0/22**(上限12.7%)。評価者とrollback_Xの3値ラベル不一致 **0件**(30判定中)。")
w("- ただしRollbackの内訳は 正%d/曖%d/誤0(JA R2)で、**曖昧が9/10**(過去12本は曖昧9/12=75%%)。固定最小Note(brief到達10/10)でも『正』は増えていない(JA R2 正1/10、過去 正3/12)。Noteの効果は曖昧→正の方向では確認できない。" % (R["ja_r2"]["eval"]["correct"], R["ja_r2"]["eval"]["ambiguous"]))
w("- Gate STOP(1回目) 2/18(懸念なし)。原価 平均¥10.43・最大¥18.50・総額(失敗試行込み)¥195.5(合格)。Rewrite由来の新規重大 0。")
w("- **要注意1点**: ④不要Rewrite率。事前登録文言(unclearは分子に含めず別掲)=**%s**(`>50%%`に該当せず)、委任文の定義(before_was_ng=false+unclear)=**%s**(`>50%%`で要注意)。事前登録の定義は変えず両方を併記し、裁定はFableに委ねる。" % (pct(A["unneeded_rate_strict_false_only"]), pct(A["unneeded_rate_false_or_unclear"])))
w("- 暫定の総合判定: 事前登録の文言を機械適用すると **PASS(暫定)**、委任文の不要定義を適用すると **CONDITIONAL(暫定)**。いずれも「N=18の範囲で検出されなかった」であり安全の証明ではない。")
w("")
w("## ①〜⑦ 事前登録指標(数値)")
w("### ① Rollback(Meta N=10、HC-012選択10/10、not_selected 0)")
w("| 箇所 | 評価者 正/曖/誤 | rollback_X 正/曖/誤 |")
w("|---|---|---|")
for st, nm in (("ja_r2", "JA R2(主指標①a)"), ("en_pre_checker", "EN Checker前"), ("en_final", "EN最終(Checker後)")):
    e, x = R[st]["eval"], R[st]["X"]
    w("| %s | %d/%d/%d | %d/%d/%d |" % (nm, e["correct"], e["ambiguous"], e["misread"], x["correct"], x["ambiguous"], x["misread"]))
we, wx = R["worse_of_3"]["eval"], R["worse_of_3"]["X"]
w("| 3箇所の悪い方(①b) | %d/%d/%d | %d/%d/%d |" % (we["correct"], we["ambiguous"], we["misread"], wx["correct"], wx["ambiguous"], wx["misread"]))
w("")
w("- X判定と記事評価者判定の不一致: **%d件**(10記事x3箇所=30判定すべて一致)。" % len(A["rollback_disagree"]))
w("- 『正』の記事: JA R2 は cz6g(rep4)のみ。ua6f(rep7)は JA が曖昧、EN(Checker前=最終)が『put on hold』で正(悪い方=曖昧)。")
c = R["cumulative"]
w("- **累積(過去12本+今回10本=N=%d)**: 正%d/曖%d/誤%d。誤読0/%d、片側95%%上限 **%s**(今回のみ 0/10=%s)。過去内訳は REPORT §91(5本: 正1/曖4/誤0)+§92(7本: 正2/曖5/誤0、rep9境界は曖昧扱いで固定)。" % (c["n"], c["correct"], c["ambiguous"], c["misread"], c["n"], pct(c["misread_upper95"]), pct(R["new_misread_upper95"])))
w("- EN Checker前→EN最終でラベル変化 0件(Checkerは Meta HC-012 文を変更していない)。")
w("- 判定: ①a=**%s**(暫定)。" % J["1_rollback"])
w("")
w("### ② 重大NG(18本)")
w("- 重大あり記事 **%d/18**、重大NG件数 %d(全工程)。pendingで leaning=major とされた件 %d。片側95%%上限 15.3%%(0/18)。V0 0/55(5.3%%)とは別条件(Checkerあり・Meta Note混入・N=18)であり同一条件比較ではない。" % (len(A["major_articles"]), S["major_all"], len(A["pending_leaning_major"])))
w("- 評価者が『重大寄りの境界』と書いたのは ai_control/jb9k item3(軽微に倒した)のみ明示。他の『境界』記述は軽微/Rollback関連。第2評価(重大記事の再評価)は重大0のため対象なし。判定: **%s**(暫定)。" % J["2_major"])
w("")
w("### ③ Gate STOP/生成不能")
w("- 1回目Writer内部Gate STOP **%d/18**(meta rep6、rep9。ともにphase2の JA_RECHECK_REQUIRED/JA_FACT_CHECK_STOP、同枠1回再実行で完走)。再実行後の生成不能 0。基準 ≤2/18=**%s**。V5 4/12、V0 0/12、E2E_02 P2 1/10と比較。" % (A["gate_stop_first"], J["3_gate"]))
w("- 参考(別掲): Checker final_state=STAGE4_ESCALATION が space_weapons/control rep1(4mjq) 1/18(blocking_confirmed_unlocatable_after_cap、cycle3)。これは Writer内部Gate STOPではなく③には含めない。評価対象のEN最終は重大0だが、Production経路ではStage4(人間確認)へ回る状態であり、**Fableへ要報告**(自己判断で扱いを変えない)。")
w("")
w("### ④ 不要Rewrite率")
bw = A["before_was_ng"]
w("- Checker Rewrite記録 run_facts=**%d件**(6 run)。評価者が `checker_rewrites` に記録したのは **%d件**(6記事)。**2件は評価者記録なし**(4mjq: records 2に対し評価1、kfuf: records 2に対し評価1。cycleをまたぐ同一箇所の重複/連続書換と推定、未確認)。分母は評価者記録の%d件。" % (A["rewrite_records_run_facts"], A["rewrite_evaluated"], A["rewrite_evaluated"]))
w("- before_was_ng: true %d / false %d / unclear %d。" % (bw["true"], bw["false"], bw["unclear"]))
w("- 不要率(false+unclear)=**%d/%d=%s**。事前登録文言(falseのみ)=%d/%d=%s。記事単位: Rewrite入り6記事のうち全件が不要(true無し)= %s(%d/6)、falseのみ= %s。" % (bw["false"] + bw["unclear"], A["rewrite_evaluated"], pct(A["unneeded_rate_false_or_unclear"]), bw["false"], A["rewrite_evaluated"], pct(A["unneeded_rate_strict_false_only"]), ",".join(A["rewrite_articles_all_unneeded_incl_unclear"]), len(A["rewrite_articles_all_unneeded_incl_unclear"]), ",".join(A["rewrite_articles_all_false"])))
w("- 必要だったRewrite(true): ai_control/jb9k(『AISI事案』帰属補足)、meta/qvqc(情報共有可能性の拡張除去)の2件。不要寄り: gj99・jdmu(unclear)、qvqc タイトル・qvqc『sometimes a human』(false)、4mjq『four faces』文削除(false)、kfuf限定文削除(false)。")
w("- 不要率>50%は『要注意』としてFable報告(事前登録④)。合否基準なし。")
w("")
w("### ⑤ Rewrite由来の新規NG")
w("- after_new_ng: **major %d** / minor %d(meta/qvqc タイトル変更『I Followed…』→『Meta Tested an AI Phone Agent and Found a Human』で主体が曖昧化)。Checker前ENに無く最終ENで新規に生じたNG(s2のみ)= %d件(同じqvqc-03)。基準 major=0 → **%s**(暫定)。" % (A["new_ng_from_rewrite"]["major"], A["new_ng_from_rewrite"]["minor"], len(A["s2_only_items"]), J["5_new_major"]))
w("- 逆に、Checkerが ENだけ解消したNGは jb9k-01(AISI帰属)・qvqc-02(情報共有の拡張)で、いずれもJAには残存(⑦参照)。")
w("")
w("### ⑥ 原価(TTSなし)")
w("- 平均 **¥%.2f**・最大 **¥%.2f**(meta rep2)・完了18本総額 ¥%.2f・失敗試行込みディスク総額 **¥%.2f**。基準 平均≤¥13.0・最大≤¥25・総額≤¥500 → **%s**。参照 TRIAL-04 Control平均¥9.28、E2E_02 P2平均¥11.04/最大¥16.74。" % (A["cost"]["avg"], A["cost"]["max"], A["cost"]["completed_total"], A["cost"]["disk_total_incl_failed"], J["6_cost"]))
w("")
w("### ⑦ JAのみ残存NG(OPEN-239関連、Checker書換はENのみ)")
w("- 件数 **%d件**(重大0/軽微%d): " % (len(A["ja_only_items"]), len(A["ja_only_items"])) + "、".join("%s %s(%s)" % (k, i.split("-")[-1], kind) for k, i, sv, kind in A["ja_only_items"]) + "。いずれも軽微。")
w("")
w("## 軽微NGの集計(HC-012 Rollback曖昧を分離)")
w("定義: 全工程=ng_items全件(R0/JA R2/ENのいずれかに存在、同一誤り1件)、JA/EN最終=s1またはs2に残存。『Rollback曖昧』=fact_id=MUSE-HC-012 かつ kind=scope のng_items(Rollback 3値と二重計上になる)。")
w("| 区分 | 軽微(全工程) | 軽微/記事 | 軽微(JA/EN最終) | 軽微/記事 |")
w("|---|---|---|---|---|")
w("| 含む(18記事) | %d | %s | %d | %s |" % (S["minor_all"], f(S["minor_all"], 18), S["minor_final"], f(S["minor_final"], 18)))
w("| うちRollback曖昧 | %d | - | %d | - |" % (S["minor_rb"], S["minor_final_rb"]))
w("| **Rollback曖昧を除く** | **%d** | **%s** | **%d** | **%s** |" % (S["minor_excl"], f(S["minor_excl"], 18), S["minor_final_excl"], f(S["minor_final_excl"], 18)))
w("| (参考)jb9k除く17記事、Rollback曖昧除く | %d | %s | %d | %s |" % (A["excl_jb9k"]["minor_excl"], f(A["excl_jb9k"]["minor_excl"], 17), A["excl_jb9k"]["minor_final_excl"], f(A["excl_jb9k"]["minor_final_excl"], 17)))
w("")
w("- 注: 件数25→うちRollback曖昧**9**→それ以外**16**(委任文の例示は10だが、cz6g(正)はRollback曖昧に該当せず、実数は9。Rollback 3値の曖昧=JA R2 9件と一致)。")
w("- 比較(同一物差し、`SUMMARY_RCA.md`): B3 V0(Checker無)12記事 全工程0.58/最終0.58、重大0/12。E2E_02従来(Note無、Checkerあり)5記事 全工程1.40/最終0.60、重大0/5。")
w("- 全工程の軽微/記事: 今回 含む%s・除く%s ≷ V0 0.58 / E2E_02従来 1.40。JA/EN最終: 今回 含む%s・除く%s ≷ V0 0.58 / E2E_02従来 0.60。" % (f(S["minor_all"], 18), f(S["minor_excl"], 18), f(S["minor_final"], 18), f(S["minor_final_excl"], 18)))
w("- 読み方: Rollback曖昧を除いてもV0(0.58)よりやや多いが、評価者間の差が大きく(下記)、N=18・単独評価のためこの差だけで悪化とは言えない。E2E_02従来(1.40)とは同水準以下。**jb9k(1記事で5件)が全体を押し上げている**(jb9k除く17記事・Rollback除く=%s/記事)。" % f(A["excl_jb9k"]["minor_excl"], 17))
w("- 退行(R0→R2、軽微): %d件(meta 4、ai_control 2。jb9k 2件、meta 2xhw/cz6g/jdmu 2件)、重大0。V0 0.08/記事より多い(%s/記事)。内訳にjdmuのHC-012(ロールバックのまま曖昧化)を含む。" % (S["reg_minor"], f(S["reg_minor"], 18)))
w("")
w("## テーマ別(重大/軽微/保留/退行)")
w("| テーマ | 記事 | 重大 | 軽微(全工程、含む) | 軽微(Rollback曖昧除く) | 軽微(最終) | 保留 | 退行 |")
w("|---|---|---|---|---|---|---|---|")
for t in ("meta", "hormuz", "space_weapons", "sewer", "ai_control"):
    g = T[t]
    w("| %s | %d | %d | %d(%s) | %d(%s) | %d | %d | %d |" % (t, g["n"], g["major_all"], g["minor_all"], f(g["minor_all"], g["n"]), g["minor_excl"], f(g["minor_excl"], g["n"]), g["minor_final"], g["pending"], g["reg_minor"]))
w("")
w("- **ai_control/jb9k(評価C)**: 軽微5・退行2・保留1。内容=『AISI事案の封じ込め帰属が不明(JA)』『別の内部テストの一般化』『AIが外へ流れ出した事実も報告されていません(台帳の自己持ち出しなしを、直前の外部到達記述と矛盾して読める否定文にした。評価Cは重大寄りだが軽微に倒した)』『R2で現時点で人間が制御を失ったわけではないへ一般化』『防御策の対象取り違え』。Checkerは帰属補足1件(必要なRewrite)のみ。※ai_control s9dk は軽微1(認証情報流出元の限定)。")
w("- hormuz 2記事は重大・軽微とも0(保留4: 出典帰属・Trump発言の強さ等)。space_weapons: 4mjq軽微1(counterspaceの連結)・kfuf 0、Checker STAGE4_ESCALATION 1件(4mjq)。sewer: 軽微2(うち1件はR0のみ)。")
w("")
w("## 評価者別(評価者効果)")
w("| 評価者 | 記事数 | 重大 | 軽微(全工程、含む) | 軽微/記事 | Rollback曖昧除く | 軽微/記事 | 保留 |")
w("|---|---|---|---|---|---|---|---|")
for e in ("A", "B", "C"):
    g = E[e]
    w("| %s | %d | %d | %d | %s | %d | %s | %d |" % (e, g["n"], g["major_all"], g["minor_all"], f(g["minor_all"], g["n"]), g["minor_excl"], f(g["minor_excl"], g["n"]), g["pending"]))
w("- 評価Cの軽微/記事が最大(担当にjb9k=軽微5を含む)。除外後も評価者間でC>A>B(1.50/0.67/0.50)。別TrialのRCA再採点でも評価者別に0.56〜1.22/記事と開きがあり(SUMMARY_RCA §4)、評価者効果は大きい。割付(どの記事が誰か)の偶然を含むため、V0/E2E_02との差は評価者を揃えた比較ではなく参考値。")
w("")
w("## 事前登録の総合判定規則の機械適用(暫定、人間確認前)")
w("| 指標 | 結果 | 判定 |")
w("|---|---|---|")
w("| ①a Rollback JA R2 誤読 | 0/10(累積0/22) | %s |" % J["1_rollback"])
w("| ② 重大あり記事 | 0/18 | %s |" % J["2_major"])
w("| ③ Gate STOP(1回目) | 2/18 | %s |" % J["3_gate"])
w("| ④ 不要Rewrite率 | 50.0%(false) / 75.0%(false+unclear) | 要注意判定が定義で分かれる(上記) |")
w("| ⑤ Rewrite由来の新規重大 | 0 | %s |" % J["5_new_major"])
w("| ⑥ 原価 | 平均¥10.43/最大¥18.50/総額¥195.5 | %s |" % J["6_cost"])
w("- **規則どおりの暫定判定**: 事前登録の文言(④分子=falseのみ、50.0%%)=**%s**。委任文の不要定義(unclear含む75%%、`>50%%`で要注意→CONDITIONAL条項)=**%s**。" % (J["overall_prereg_text"], J["overall_if_unclear_counted"]))
w("- いずれも、(a)人間確認でRollback/重大の確定がなされるまで暫定、(b)『N=18の範囲で検出されなかった』であり安全の証明ではない、(c)Production採用は人間ユーザーのみ。")
w("- 目的(1)Rollback N増し: 累積0/22(上限12.7%)達成。曖昧が22中18件(82%)残存=固定最小Noteで曖昧→正にはほぼ動かない。目的(2)本番経路のネガ: 重大・新規重大は見当たらず、要注意は④(不要Rewrite)とCheckerのSTAGE4_ESCALATION 1件、評価者C側のjb9k集中。")
w("")
w("## plan §2(a): themeの渡し方の影響評価(事実)")
w("- 今回18本は `--theme` に `topic.txt` の**内容**を渡した。TRIAL-04 Control(5本)・E2E_02(allfact_note_e2e_02、全run)の `entry_point.json` の `args.theme` は `er052_output/open233_polysemy_trial_02/ledgers/<slug>/topic.txt` という**パス文字列そのもの**だった(確認済み)。")
w("- runner(er019)は `args.theme` を文字列のまま B3のstoryline/事実選択プロンプトの `{topic}` へ埋め込む(ファイルを読まない。コード上 `isfile/open` なし)。よって当時のStoryline/選定はテーマ文ではなくパス文字列を受けており、今回はテーマ文本体を受けた。台帳(`--ledger-txt`固定sha)は同一でresearchは0回のため、差が出るのは storyline_b3(brief)の入力のみ。")
w("- 比較への影響: brief生成の入力条件が異なる(Control再確認の同一条件比較ではない)。方向と大きさは本データからは分離不能(未測定)。hormuzの内容テーマ文は『見出し行+代替採用の註記』を含む文字列だった点も同様に条件差(参考)。V0/E2E_02従来との対比は『参考値』扱いとする。")
w("")
w("## Note位置(rep10 249j)")
w("- rep10(249j)はNoteがHC-012 factの直後でなく冒頭Storyline行の直前(brief 8行目、HC-012は11行目)。249j のRollbackは JA/EN前/EN最終とも曖昧(評価者・X一致)、誤読ではない。位置不良が結果を変えた証拠はない(rep1〜9でNote隣接でも正は cz6g・ua6f(EN)のみ)。詳細は `HUMAN_REVIEW_PACK.md` の(d)。")
w("")
w("## 付録: 生成物")
w("- `eval/aggregate_ccp.json`(数値の正)、`docs/pm/control_checker_polysemy_trial_01/tools/aggregate_eval_ccp.py`・`build_summary_ccp.py`(再現script、API無し)。人間確認パック=`eval/HUMAN_REVIEW_PACK.md`。")
open(EV + "/SUMMARY_CCP.md", "w", encoding="utf-8").write("\n".join(L) + "\n")
print("ok", len(L))
